### ISSUE TITLE
Consider updating/maintaining this repo?

### ISSUE THREAD

**Issue by Claw256** [pwssnk/py-usvfs#1]
Hi,
I can across your python wrapper for USVFS, and I am very enthusiast about using it, and I am thankful that you have made it. Would you consider updating/maintaining the project, as the last commit was in July of 2019, and I'm sure that MO2/USVFS has advanced alot since then.

Thanks,

-Claw

**Comment by pwssnk** [comment]
Hi Claw,

Glad you find  this little project useful. Unfortunately, I do not have the time or interest to actively maintain it. Future updates may or not come, but they will always be sporadical at best.  
Of course, you are welcome to fork the repository and update the project as needed. I am happy to consider pull requests for any updates.
